### ISSUE TITLE
Improve documentation at dockovpn.io

### ISSUE THREAD

**Issue by Krock21rus** [dockovpn/docker-openvpn#122]
Tried guide from https://dockovpn.io/, something went wrong
Tried to start again, got
"docker: Error response from daemon: Conflict. The container name "/dockovpn" is already in use..."
This should be fixed by adding --rm option, cause docker container had status EXITED in my case
Also, there is no information about stopping/restarting VPN in https://dockovpn.io/

**Comment by alekslitvinenk** [comment]
Thanks for the feedback, we're checking the issue. The problem with --rm option is that many customers still want to use the container after it was stop. 
We will test the possibility to add this flag after making sure mounted volume fully saves the state of container

**Comment by Krock21rus** [comment]
Also, the command runs in interactive mode, so the client can't close the terminal
Please consider adding -d option(and docker logs dockovpn for HTTP::??.??.??.??), or guide with screen or tmux

**Comment by Krock21rus** [comment]
I have changed the topic.
https://dockovpn.io, https://dockovpn.io/docs/quickstart/ and README.md help only to run VPN server once, as an experiment but gives no information about supporting and running it's as a permanent VPN server on vps/vds.
For example, I think it's important to mention about --rm option in docker, -d option in docker, "docker rm dockovpn" if something went wrong

**Comment by alekslitvinenk** [comment]
Thanks a lot for the feedback! Yes, the documentation definitely needs some improvement!

**Comment by alekslitvinenk** [comment]
Created #123  to address issues with conflicting containers and stopped container when ssh session terminates.

This (current) issue shall be solved after #123

**Comment by alekslitvinenk** [comment]
Fixed in #123
