### ISSUE TITLE
Default TCP/HTTP server port

### ISSUE THREAD

**Issue by DimaDDM** [dockovpn/docker-openvpn#131]
Hello. Can you change option for change default TCP/HTTP server port? When i'm run docker container with `-p 80:8080/tcp` and with nginx on server i got error about port binds (Can't bind cause port 80 already in use). When i'm trying change port - OpenVPN config file won't downloading

**Comment by alekslitvinenk** [comment]
You can bind to another port. For instance you can use `-p 8080:8080/tcp`, but container itself wouldn't know that you bind to a different than default http port and will still generate link without custom port... You need to append corresponding port component yourself

**Comment by DimaDDM** [comment]
> You can bind to another port. For instance you can use `-p 8080:8080/tcp`, but container itself wouldn't know that you bind to a different than default http port and will still generate link without custom port... You need to append corresponding port component yourself

Can this issue will be fixed? `-p 8080:8080/tcp` not work properly for me. Link  just not work. Maybe you can rebind http server to random port for compatibility?

**Comment by alekslitvinenk** [comment]
Why doesn't link fork for you? What config fo you run container with and what link do you try to get configuration from?
